import crypto from 'node:crypto';
import { Injectable, NestMiddleware } from '@nestjs/common';
import { Request, Response, NextFunction } from 'express';
import { FastifyRequest } from 'fastify';

/**
 * TraceIdMiddleware — sets x-trace-id header and stores traceId on request.
 *
 * Uses the request.id generated by hyperid (configured in main.ts FastifyAdapter),
 * or falls back to crypto.randomUUID().
 *
 * NOTE: Uses Express-compatible signatures for NestMiddleware compatibility.
 * At runtime the raw Node.js ServerResponse is used (Fastify adapter).
 */
@Injectable()
export class TraceIdMiddleware implements NestMiddleware {
  use(req: Request, res: Response, next: NextFunction) {
    const fastifyReq = req as unknown as FastifyRequest;
    const traceId = (fastifyReq.id as string) || crypto.randomUUID();
    res.setHeader('x-trace-id', traceId);
    // Store traceId on request for use by AllExceptionsFilter
    (req as any).traceId = traceId;
    next();
  }
}
