version: '3.9'
services:
  api-user:
    build: .
    image: leandrojaviercepeda/api-user:${TAG}
    container_name: api-user
    restart: always
    ports:
    - ${PORT}:${PORT}
    env_file:
    - .env.${NODE_ENV}