services:
  db-user:
    image: mongo:6.0.3
    container_name: db-user_${NODE_ENV}-${VERSION}
    expose:
      - 27017
    restart: always
    ports:
      - ${DATABASE_PORT}:27017
    volumes:
      - api-user-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    networks:
      - default

  api-user:
    image: countergank/api-user:${NODE_ENV}-${VERSION}
    container_name: api-user_${NODE_ENV}-${VERSION}
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    depends_on:
      - db-user
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - .:/usr/src/app
    networks:
      - default

volumes:
  api-user-data:
    driver: local

networks:
  default:
    name: api-user-net
    driver: bridge

  # microservice-name-net:
  #   name: microservice-name-net
  #   external: true
