version: '3.5'
services:
  api-user:
    build:
      args:
      - PORT=${PORT}
    image: leandrojaviercepeda/api-user:${TAG}
    container_name: api-user
    restart: always
    ports:
    - ${PORT}:${PORT}
    env_file:
    - .env.${NODE_APP_INSTANCE}