version: '3.9'
services:
  api-user:
    image: countergank/api-user:${NODE_ENV}-${VERSION}
    container_name: api-user_${NODE_ENV}-${VERSION}
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    command: npm run start:debug
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env.${NODE_ENV}
    volumes:
      - .:/usr/src/app
    networks:
      - api-user

networks:
  api-user:
    name: api-user_${NODE_ENV}-${VERSION}
    driver: bridge
