on:
  pull_request:
    branches: [develop, qa, master]
name: release-docker-image
jobs:
  build-push-image:
    name: Build & Push image
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        id: extract-branch-name
        run: echo "::set-output name=branch_name::${{ github.base_ref }}"

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.extract-branch-name.outputs.branch_name }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read package.json version
        id: read-version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "Version from package.json: $VERSION"
          echo "::set-output name=TAG::$VERSION"
        working-directory: ${{ github.workspace }}

      - name: Login to Docker Hub ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          images: ${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags:
            ${{ github.repository }}:${{ steps.extract-branch-name.outputs.branch_name }}-${{ steps.read-version.outputs.TAG }},
            ${{ github.repository }}:${{ steps.extract-branch-name.outputs.branch_name }}-latest
